version: '3'

services:
  book_api:
    build: .
    depends_on:
      - localstack
    ports:
      - '3000:3000'
    container_name: book_api

  localstack:
    image: localstack/localstack:latest
    ports:
      - '8000:8000'
    container_name: dynamodb_book_api_localstack
    environment:
      SERVICES: dynamodb:8000
      DATA_DIR: '/tmp/localstack/data'
